if (typeof define !== 'function') {
    var define = require('amdefine')(module);
}

define(['vendors/utili/q'], function(Q){
    function Login(mysqlPool){
        /**
         * login by session hash
         * @param {String} session - a session hash that is generated by a Session
         * @returns {Promise} Promise - fulfill promise if the session hash exists 
         * with a userData Object that includes the session hash and other values 
         * otherwise the promise will be reject
         */
        this.bySession = function(session){
            return Q.Promise(function(resolve, reject){
                
                mysqlPool.query(
                    'SELECT * FROM loginSession\n' +
                    'LEFT JOIN user ON user.id = loginSession.uid\n' +
                    'WHERE hash = ?\n' +
                    'LIMIT 1',
                    [session],
                    function(error, rows){
                        // something wents wrone
                        if(error){
                            console.log(error);
                            reject(error);
                        // no session or user found
                        }else if(rows.length <= 0){
                            reject();
                        // user found
                        }else{
                            var result = rows[0];
                            resolve(result);
                        }
                    }
                );
            });
        };
        /**
         * login by email and password
         * @param {String} email
         * @param {String} password
         * @returns {Promise} Promise - fulfill promise if the user exists with a userData 
         * Object otherwise the promise will be reject
         */
        this.byAuth = function(email, password){
            return Q.Promise(function(resolve, reject){
                mysqlPool.query(
                    'SELECT * FROM user\n' +
                    'WHERE email = ? and password = PASSWORD(?)\n' +
                    'LIMIT 1',
                    [email, password],
                    function(error, rows){
                        // something wents wrone
                        if(error){
                            console.log(error);
                            reject(error);
                        // no user found
                        }else if(rows.length <= 0){
                            reject();
                        // user found
                        }else{
                            var result = rows[0];
                            resolve(result);
                        }
                    }
                );
            });
        };
    }
    return Login;
});